### PR TITLE
Adding a SpellCheckSuggestions function

### PR DESCRIPTION
**Pull request by sparrc**
This is for the purpose of getting back multiple spellcheck suggestions,
similar to Suggestions but in an ordered list of best to worst.

### CODE REVIEW

**Comment by sparrc** [comment]
For a little more context, I needed a combination of the Suggestions() function and SpellCheck() function. Instrumenting that from the outside would require a lot of code duplication since best() is a private function

**Comment by sparrc** [comment]
bump, can anyone take a look at this PR? I'd love to get it merged!

As far as I can tell, the travis container just ran a benchmark test that had nothing to do with my change too slowly?

**Comment by sparrc** [comment]
Also it looks like it may have passed on Go1.4 and Go1.5, only failing on the tip of Go @mish15

**Comment by dhowden** [comment]
Sorry for the delay.  Been holding off on this change because it highlighted some further structural changes that would make things much nicer.  Sadly I've been too busy with other things to do anything about them though, so will merge this now.

The build is failing due to a flaky test (unrelated to your change) which needs to be fixed/removed.

**Comment by mish15** [comment]
hey @sparrc yep my flaky test! This is all good. :)

**Pull request merged**
